paolosalvatori/ServiceBusExplorer

Helpers/ConversionHelper.cs
We have a custom property of type DateTime on our messages, so when resubmitting from the Dead Letter queue, we need that property to go along with the message.
=> Allow Custom DateTime Properties when re-submitting

Controls/HandleNotificationHubControl.cs
When APNS had been configured and there was updated the notification hub
registration (e.g. changing of TTL), the APNS settings have been reset
to null. Similarly for MPNS.
=> Fixed resetting of ApnsCredential on notificationHubDescription update

Controls/PartitionListenerControl.cs, Helpers/MessageSerializationHelper.cs, Helpers/ServiceBusHelper.cs
Example: 
```json
[
{
"time": "2015-09-03T16:12:54.8040267Z",
"name": "PostCounter",
"value": 69445
},
{
"time": "2015-09-03T16:12:54.8040267Z",
"name": "Value_114779289",
"value": 13.94
}
]
```
**Reason:** JObject.Parse rejects JSON arrays for some reason. 
**Fix:** Attempt parsing with JArray.Parse if JObject.Parse fails. 
Commit: MarkusHorstmann/ServiceBusExplorer@011e1d948d30e1fd5591736d2441c78f70d2b441
**Reason:** Multiple attempts of deserializing as XML etc. for each event, with JSON being the last one.
**Fix:** Add option to not reserialize the payload at all and instead always embed it as a string, which also come in handy as a feature when debugging payload formatting/syntax issues.
Commit: MarkusHorstmann/ServiceBusExplorer@a5aff23bdf2089afb0a615099a11f901e05d8290.
=> Event Hub "Save Selected Events" improvements

Forms/MainForm.Designer.cs, Forms/MainForm.cs
Currently one needs to use context menu and select delete option to remove a single entity.
This change allows deletion with a single delete key for convenience.
=> Allow a single entity deletion with Delete key

Controls/HandleQueueControl.cs, Forms/ConnectForm.cs
* trim whitespace from the entered ConnectionString to avoid problems when connecting
* clear the field for SessionState when switching to another session where SessionState is null
=> Trim whitespace from ConnectionString and clear SessionState when null

ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
Seems there was an incorrect hint path in the unit test project file - sorry about that.
=> Corrected hint path to nunit.framework.dll

App.config, ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, ServiceBusExplorer.Tests/app.config, ServiceBusExplorer.csproj, packages.config
Incremented nuget references to new SB SDK, which does support new German DCs (central and east)
=> Build with support for German DCs

README.md
<div>Read the full article on <a title="MSDN" href="http://msdn.microsoft.com/en-us/library/hh532261(v=VS.103).aspx" target="_blank"> MSDN</a>.</div>
*This link is broken:* http://msdn.microsoft.com/en-us/library/hh532261(v=VS.103).aspx
Not sure of the correct link to replace it with, and/or if instead it should be omitted altogether as it may no longer be relevant?
Also as I understand it the Windows Azure Management Portal is now referred to either as the "classic" portal: https://manage.windowsazure.com or the "new" portal: https://portal.azure.com/ but didn't want to change any URLs. Does the Service Bus Explorer interacts in different ways depending on which portal and their different functionalities?
=> Removing article link "This topic is no longer available"

Forms/MainForm.cs
At the startup of list of the selected entities is initialized only with the first item even more the one entity is saved in the configuration file. The configured entities are prefixed with a single space so they do not match the predefined entity names. The fix contains config values trim and a little simplification in selected list creation.
=> Fix selected entities initializing

Helpers/ConversionHelper.cs
Currently when a message wil be resubmitted and the originl message contains an custom property (aka header) of type Guid, the conversion of the values into the new message failes. This is because that in situation the datatype of the value is already a System.Guid. Converting to System.String will result in a null which will cause an exception. This fix is already done in the masterbranch.
=> Fix mapping from custom property of type Guid when resubmitting a message

Properties/AssemblyInfo.cs
Version is set by appveyor in [appveyor.xml](https://github.com/paolosalvatori/ServiceBusExplorer/blob/master/appveyor.yml#L23). Version is always is using ASBmajor.ASBminor.BuildNumber. `BuildNumber` is managed by appveyor to uniquely identify each build. Locally build versions are always 1.0.0.0
This exact issue #71 was fixed before and not it has been re-introduced in commit 7dd0063463d40213b1686fc0afcdc79a77202a94 ([line](https://github.com/paolosalvatori/ServiceBusExplorer/commit/7dd0063463d40213b1686fc0afcdc79a77202a94#diff-bd54859a3ac1af0ed67607c0767acc72R35) and [line](https://github.com/paolosalvatori/ServiceBusExplorer/commit/7dd0063463d40213b1686fc0afcdc79a77202a94#diff-bd54859a3ac1af0ed67607c0767acc72R36)).
@paolosalvatori please see above
=> Version should not be hardcoded from the code

Properties/AssemblyInfo.cs, appveyor.yml
Locally build version should be **1.0.0** as it is NOT a version pulled from a build server.
Version build on build server will be always `major.minor.patch` with increased patch on merge to `master`.
Direct commits to `master` will not result in a new patch increase.
=> assembly version

Helpers/JsonSerializerHelper.cs, ServiceBusExplorer.Tests/Helpers/JsonSerializerHelperTest.cs, ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
If the message sent to the service bus used Newtonsoft with TypeHandling defined, when indenting the string the `$type` property is dismissed by ServiceBusExplorer in Message Text components.
As we cannot use TypeHandling (ServiceBusExplorer does not know about user classes) I propose here to search and replace `$type` keyword during deserialization / serialization process.
Fix tested and approved on Service Bus Queues
=> Keep eventual root $type property in Json indentation

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.cs, src/ServiceBusExplorer/Helpers/QueueDescriptionExtensions.cs, src/ServiceBusExplorer/Helpers/SimpleSite.cs, src/ServiceBusExplorer/Helpers/TopicDescriptionExtensions.cs, src/ServiceBusExplorer/ServiceBusExplorer.csproj
Part of future 4.0.92 release
Fixes #120 and #97 
- Reflects premium tier entity size correctly (1, 2, 3, 4, 5, 10, 20, 40, 80 GB).
- Reflects standard tier entity size correctly (1, 2, 3, 4, 5 for non-partitioned and 16, 32, 48, 64, 80 GB for partitioned).
Note: creation is still not reflecting sizes as there's no way to know what namespace it is.
=> Reflect entity size correctly

Generate-VerificationFile.ps1, VERIFICATION-Template.txt, appveyor.yml
- Use template to include pointer to license & release
- Only hash ServiceBusExplorer.exe instead of all contents
- Currently only push to Chocolatey from develop branch with fixed 4.0.102 version until we pass validation via environment variable `choco_version`.
Relates to #137.
Example of VERIFICATION.txt:
```
VERIFICATION
Verification is intended to assist the Chocolatey moderators and community
in verifying that this package's contents are trustworthy.
The installer have been downloaded from their official download link listed on <https://github.com/paolosalvatori/ServiceBusExplorer/releases>
and can be verified like this:
1. Download the following installers:
64-Bit: <https://github.com/paolosalvatori/ServiceBusExplorer/releases/download/4.0.104/ServiceBusExplorer-4.0.104.zip>
2. You …
```
=> Chocolatey Verification - Use template and only hash ServiceBusExplorer.exe

src/ServiceBusExplorer/Controls/HandleNotificationHubControl.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs
https://youtu.be/Nl82ePL8nLE
https://youtu.be/qSw5AHzIUyw
The video is still processing. But the TLDR version is that deleting is with my example here is almost one minute faster.
=> Async delete

appveyor.yml
Add resiliency for Chocolatey.
Tested this on my fork [here](https://ci.appveyor.com/project/tomkerkhove/servicebusexplorer-7bhx3/build/1.0.10, packing still works but pushing has obviously not been tested.
Relates to #154.
=> Add Resiliency for Chocolatey

src/ServiceBusExplorer/Forms/MessageForm.Designer.cs, src/ServiceBusExplorer/Forms/MessageForm.cs
This change resolves #145. I added a new checkbox near the submit button. When checked, the submit process will generate new IDs for the message(s).
Not the best solution from a user experience standpoint, but after thinking about this quite a while this is the best solution I came up with without making larger changes to the UI.
=> Make it possible to generate fresh MessageId on submit

.gitignore
May I suggest you include .vs as an ignore pattern in .gitignore? Otherwise git clients start to pick up on the .vs folder which should not live under version control.
=> Add Visual Studio's .vs folder to gitignore

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
Fixes #96 where purging failed from a subscription that requires a session. The bug also mentions queues, and this PR also fixes the issue with queues.
=> Support purge from queues and subscriptions that require a session

src/.editorconfig, src/ServiceBusExplorer.sln
Resolve #160 by adding an `.editorconfig` file. This will instruct the editor (VS2017, previous VS versions require a plugin installed) to use 4 spaces for indenting `.CS` files and 2 spaces for indenting `.config` files.
=> Added .editorconfig to project #160

src/ServiceBusExplorer/Helpers/BrokeredMessageExtensions.cs
This solves #166, the issue with ContentType being lost when resubmitting message with body type byteArray.
I have tested that it works as intended, but I am unsure how to test if it breaks any existing behavior.
=> Closes #166 by setting ContentType and Label

src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs, src/ServiceBusExplorer/Helpers/ServiceBusNamespace.cs
I'd like to close #139 (Access individual entities w/o permission to the entire namespace) with this PR.
I've added a check for the entitypath when parsing the connection string. This then flows into additional checks in the ServiceBusHelper class so that it doesn't try to query for all Topics or Queues when an EntityPath has been provided (otherwise a permissions exception is thrown). 
The logic for getting queues and topics have been placed into separate methods (GetQueueUsingEntityPath and GetTopicUsingEntityPath),
I've tested the changes against Azure Service Bus with a full Administrative connection string and one that is limited to a single topic and one that is limited to a single queue. I've not been able to test the application against Windows Service Bus as I don't have access …
=> Added support for EntityPath in the connection string

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
Fixes #174 and #176 
Removed some ConfigureAwait(false) calls to keep the synchronization context since it is required to interact with the UI components in the later parts of the Purge methods.
Also removed the UseWaitCursor calls when purging from the MainForm.
=> Removed ConfigureAwait and UseWaitCursor calls to fix #174 and #176

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs, src/ServiceBusExplorer/Helpers/MessagingPurger.cs, src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs, src/ServiceBusExplorer/ServiceBusExplorer.csproj, src/ServiceBusExplorer/packages.config
Attempts to fix #60. There are many variations with partioned entities, session entities, message size, network latency and other factors so the code will probably have to be tuned.
I used VS automatic formatting and it did a lot of formatting on other places too. I thought I'd leave those changes since I think it looks better and will take a while to undo. 
I had some issues with entities with sessions so only one receiving task is used for them. I upgraded to the latest Service Bus client, but it didn't help. But that is how I have tested this so the code upgrades the Service Bus client to the latest version.
I moved code from the HandleQueueControl and the HandleSubscriptionControl classes to a new class called MessagingPurger where subscriptions and queues are handled in basically the …
=> More reliable and faster purging of messaging entities, fix for #60

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Helpers/MessagingPurger.cs
Fixes #183 
I took the liberty to clean up the class a little bit and remove some redandencies.
Couldn't figure out what to do about https://github.com/paolosalvatori/ServiceBusExplorer/commit/63e6c9d67f14e31b54d0e7ee12fbff4447a07d4e. @paolosalvatori should that method be entirely removed as it was (and is not) ever called?
=> Purging DLQs with a single message

src/ServiceBusExplorer/Forms/MessageForm.cs
I believe this fixes #173.
This change makes SBE send messages one by one instead of trying to send all the selected messages in a batched message. The reason I made this change is that it will now allow a lot of messages to be submitted, instead of being limited to the maximum message size which currently is 256 KB or 1 MB depending upon SB SKU. The only disadvantage I see is that the risk of not sending all messages increases. Therefore SBE will now display a MessageBox if not all messages were sent.
=> Send messages one by one when using Repair and Submit in Batch Mode

src/ServiceBusExplorer.Tests/Helpers/JsonSerializerHelperTest.cs, src/ServiceBusExplorer/Helpers/JsonSerializerHelper.cs
Json.NET interprets strings as date by default as discussed on https://github.com/JamesNK/Newtonsoft.Json/issues/862
So a deserialize/serialize roundtrip may actually modify the source JSON. Using `DateParseHandling = DateParseHandling.None` ensures that dates are not interpreted and thus the serialized JSON is identical to the source (except for indentation of course).
=> Do not alter dates when indenting JSON

src/ServiceBusExplorer/Controls/HandleConsumerGroupControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleEventHubControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleNotificationHubControl.designer.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleRelayControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.Designer.cs, src/ServiceBusExplorer/Controls/ListenerControl.Designer.cs, src/ServiceBusExplorer/Controls/PartitionListenerControl.Designer.cs, src/ServiceBusExplorer/Controls/TestEventHubControl.Designer.cs, src/ServiceBusExplorer/Controls/TestQueueControl.Designer.cs, src/ServiceBusExplorer/Controls/TestRelayControl.Designer.cs, src/ServiceBusExplorer/Controls/TestTopicControl.Designer.cs, src/ServiceBusExplorer/Forms/EventDataForm.Designer.cs, src/ServiceBusExplorer/Forms/MessageForm.Designer.cs, src/ServiceBusExplorer/Forms/TextForm.Designer.cs
This is especially important for message text boxes where a message could exceed the 32 KB limit.
=> Remove default max length of 32767 for most text boxes

src/ServiceBusExplorer/Forms/MainForm.cs
This should fix #213. I have tried it with namespaces only containing one of the following types:
- Event hubs
- Relay
- Basic ServiceBus namespace
and unlike Tom I had no issues. Perhaps different age/versions of the namespaces or SKUs. I was unable to connect to a Notification Hubs namespace before and after this change.
=> Fix the exception when there are no Notification hubs

src/ServiceBusExplorer/Controls/HandleConsumerGroupControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleConsumerGroupControl.cs, src/ServiceBusExplorer/Controls/HandleEventHubControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleEventHubControl.cs, src/ServiceBusExplorer/Forms/ContainerForm.cs
HandleEventHubControl:
- Replaced control for Message Retention in Days from TextBox to TrackBar
- Added code to TextChanged event for the Relative URI TextBox to lowercase the text as a user enters the name of a new Event Hub
- Changed the minimum number of partitions for an Event Hub from 8 to 2
HandleConsumerGroupControl:
- Added code to TextChanged event for the Consumer Group Name TextBox to lowercase the text as a user enters the name of a new Consumer Group
ContainerForm:
- Changed the code of the ContainerForm to explicitly add the Event Hub and Consumer Group name to the title bar when opening the form for an Event Hub Listener
=> Changes to Event Hub and Consumer Group controls

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
Fixed problem with new FastColoredTextBox: when selecting a deadletter message in the grid inside the queue or subscription, I was assigning the formatted text to the wrong textbox control.
=> Fixed minor issue with FastColoredTextBox controls

src/ServiceBusExplorer/Forms/ContainerForm.cs
When creating an event hub listener an exception occurred as HeaderTextConsumerGroupListenerFormat expects two strings (interpolation) - hub name and consumer group but only consumer group was passed
=> Fixed missing event hub name

src/ServiceBusExplorer/Forms/ContainerForm.cs
Added missing hubName expected by the string interpolation in ConsumerGroupListenerFormat
=> Added missing hubName

src/ServiceBusExplorer/Controls/HandleQueueControl.cs
Fixes #297
Whenever a DLQ-ed message details form was closed, the main form was refreshed and retrieved all queues/topics/subscriptions. This is undesirable when just inspecting DLQ-ed messages.
=> Do not refresh list of queues/topics when closing dead-lettered message inspection window.

src/ServiceBusExplorer.Tests/Helpers/ConversionHelperTests.cs, src/ServiceBusExplorer/Forms/MessageForm.cs, src/ServiceBusExplorer/Helpers/ConversionHelper.cs
PR adds a support for TimeSpan property type to the MessageForm.
It also logs info when timespan is not valid.
```
<17:31:44> The following validations failed:
- RetryInterval property conversion error: String was not recognized as a valid Boolean.
```
Question: I just noticed that my IDE removed redundant white characters. Should I bring them back?
Fixes #304
=> TimeSpan support for the Custom Properties

src/ServiceBusExplorer/Forms/MainForm.Designer.cs, src/ServiceBusExplorer/Forms/MainForm.cs
Fixes #308 - Very slow loading times for topics with a high number of subscriptions.
Topic Subscription nodes will now load a blank "Rules" node, and the real Rules will only be read from the server when the Subscription is selected or expanded. This speeds up the loading of Topics with hundreds of Subscriptions by an order of magnitude.
This was achieved by extracting much of the GetEntities() method which builds the tree into a LazyLoadNode() method. This will still add the Subscription nodes, but then adds the Rules to a list of items still be read and processed only when a Subscription node is clicked or expanded.
=> Lazy load subscription rules

README.md
The Chocolatey command is actually `choco`, not `chocolatey`, isn't it?
=> README: Fix chocolatey install command

src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs
In SBE, almost all the log messages end in a period, except for the “MessagingFactory successfully created” and “no message was received” messages. What do you think of adding periods to those, for consistency?
=> Add periods to remaining log messages

src/ServiceBusExplorer/Helpers/ImportExportHelper.cs
Currently, exported XML files are written as single lines, which makes them hard to read.
This PR enables indentation (pretty-printing) on them, so they're more readable, and can be meaningfully diffed using automated line-oriented diff tools like `diff` or git history.
Closes #322.
=> Pretty-print (indent) exported XML files

src/ServiceBusExplorer/Controls/TestRelayControl.cs, src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs
In the log messages for sending and receiving messages, SBE currently formats the “messages/second” rates using the full precision of a `double`, with about 14 digits past the decimal point.
```
- Message Count=[1] Messages Sent/Sec=[4.20168067226891] Total Elapsed Time (ms)=[238]
```
That's a wackdoodle amount of precision for the data we're looking at here. Given the actual variance in message send/receive times, and the measurement error, I'd guess there's maybe two actual significant digits of data there.
This PR reduces the excess precision here by changing the formatting of the msgs/sec values to use just 1 decimal point. Because it'll always take at least 10-20 ms to send a message, that'll be sufficient precision, and we don't need to worry about scale-independent significant …
=> Reduce excess precision in msg/sec rates in log messages

src/ServiceBusExplorer/Controls/HandleQueueControl.Designer.cs
Deadletter messages panel not showing system properties of a message.
code was setting deadletterPropertyGrid, but this was not wired up to dl message panel
remove propertyGrid1 which was present on deadletter messages panel and wire up deadletterPropertyGrid
=> Deadletter messages panel not showing system properties of a message.

src/ServiceBusExplorer/Helpers/RetryHelper.cs
Partially addresses #327.
Currently, when you attempt to create an Event Hub in a Namespace that is for Queues/Topics, or vice versa, the UI will freeze for about 30 seconds, before spewing some errors to the log. This is because the creation attempt is retried 10 times, even though this isn't a transient error.
This PR improves UI responsiveness by changing `RetryHelper` to consider `QuotaExceededException` (which is what happens in this case) to be non-transient, and not retry it.
Does not fix the UI freeze when creating Relays in a non-Relay namespace, because that throws a different `AggregateException`, which I'm not comfortable special-casing to be non-transient in this PR, unless y'all give that an explicit thumbs-up.
You could go even further along this route: `RetryHelper` …
=> Fix long delay when creating invalid entity

src/ServiceBusExplorer.Tests/Helpers/ConversionHelperTests.cs, src/ServiceBusExplorer/Helpers/ConversionHelper.cs
Resending msg fails when I want to resend msg with default, unchanged timespan value. 
It works correctly when I edit value manually, because field becomes a string property.
I have added a unit test and a fix for such issue. It avoids timespan parsing when argument is already a timespan.
=> Checking if field is already a timespan

src/ServiceBusExplorer/Forms/ConnectForm.cs
The Connection String tooltip source code is hard to read, and the long line causes a "wide" horizontal scroll bar in the editor. Would you consider reformatting it over multiple lines for readability?
=> Reformat multi-line tooltip source code for readability

src/ServiceBusExplorer/Forms/OptionForm.cs, src/ServiceBusExplorer/Helpers/MainSettings.cs
Fixes #319.
When you have set the option to use the User config file or Both config file, and then switch back to Application config file and save your settings, that change will not stick through an application restart. This is because the settings, including which config file to use, get saved to the Application file and not the User config file. So the User config file still has the old "User" or "Both" setting in it, and that will get loaded again and take precedence at the next program restart.
This PR fixes it by adding special-case logic to write the ConfigFileUse setting to the User config file if we have switched from a User-using ConfigFileUse to Application ConfigFileUse during the use of the Options form.
=> Make reversion from User config file to Application config file stick

src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Helpers/ImportExportHelper.cs
Fixes #333.
Currently, if you right-click a node in the navigation tree, select “Export <whatever>”, and then Cancel the file selection dialog, the export will abort, but you will still get log messages about “... has been successfully exported” and “Selected entities have been exported to .”.
The first is because the log messages happen when in-memory serialization from objects to XML strings happens (not when a file is written). The second is because the export code doesn't check whether the Save dialog was canceled.
This PR fixes this by:
* Adding a check for whether the Save dialog was cancelled, and suppressing the log message upon cancellation.
* Removing all the “successfully exported” log messages for XML serialization.
I realize that the latter is making a big change, but I think …
=> Fix bogus “entities exported” log message

src/ServiceBusExplorer/ServiceBusExplorer.nuspec
Rename Service Bus Explorer title to streamline Chocolatey installs.
As of today, you have to search on `ServiceBusExplorer` rather than `Service Bus Explorer`:
This is inconvenient and you have to know that you have to look it up like that as well.
This rename is also more inline with the [Chocolatey guidelines](https://github.com/chocolatey/choco/wiki/CreatePackages#naming-your-package)
=> Streamline Chocolatey install discoverability

src/ServiceBusExplorer/Helpers/ServiceBusNamespace.cs
This way we can enter an endpoint without having to type sb:// in the beginning of the text field.
=> Prepend sb:// to endpoint if not present

src/ServiceBusExplorer.Tests/Helpers/ConnectionStringHelperTests.cs, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer/Forms/ConnectForm.cs, src/ServiceBusExplorer/Helpers/ConnectionStringHelper.cs, src/ServiceBusExplorer/ServiceBusExplorer.csproj
This PR aims to fix #376 
Having run into this issue myself a few times, I decided to fix it.
While in the Save case I opted to reuse the logic provided by the connection string builder there was no such logic in the Ok button handler - the connection string is processed outside the dialog. Because it made sense to show the warning before the dialog is closed and because I did not want to add the builder there, I decided to add a simple regex verification in this case.
=> Prevent using an entity-specific connection string

src/Common/Helpers/ServiceBusHelper.cs, src/ServiceBusExplorer.Tests/Helpers/ServiceBusHelperTest.cs, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs, src/ServiceBusExplorer/Forms/MessageForm.cs, src/ServiceBusExplorer/Forms/SelectEntityForm.cs
Hello,
This PR is a proposal to better handle structured hierarchies of queues and topics when dealing with forwards.
* it exposes the **Path** relative to the namespace for **ForwardTo** and **ForwardDeadLetteredMessagesTo**
* it also ensures that when opening the queue/topic selection box for these auto-forward configuration, if an existing queue or topic is already configured, it will be focused.
I had to fix a bug in the auto focus code of the selection form to allow searching below the second level, which might contain only the part before the last slash in the queue/topic path.
Also note that this last feature will require network access to get the queue or topic from the configured Path. However, as this access will be done only on the opening of the form, I consider this is …
=> Enhance forwards UI experience

src/Common/Helpers/ConfigurationHelper.cs, src/Common/Helpers/ConfigurationParameters.cs, src/Common/Helpers/MainSettings.cs, src/ServiceBusExplorer/Controls/TestQueueControl.Designer.cs, src/ServiceBusExplorer/Controls/TestQueueControl.cs, src/ServiceBusExplorer/Controls/TestTopicControl.Designer.cs, src/ServiceBusExplorer/Controls/TestTopicControl.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Forms/OptionForm.Designer.cs, src/ServiceBusExplorer/Forms/OptionForm.cs
This PR ensures that the Content Type configured for sending message is part of the options, and will be persisted.
The rationale behind this proposal is that it is very useful for people working with systems or libraries that require specific content type to allow retaining it across executions of the tool.
An example which is very frequent for my company is to set the @MassTransit  `application/vnd.masstransit+json` content type when sending messages manually, so that the library can consume them. It would save a lot of time to be able to have the tool retain it!
The new Options UI:
The Send Message UI after doing this configuration:
=> Persist Message Content Type in the settings

src/Common/Common.csproj, src/EventHubs/EventHubs.csproj, src/NotificationHubs/NotificationHubs.csproj, src/Relay/Relay.csproj, src/ServiceBus/ServiceBus.csproj, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer/Properties/Settings.Designer.cs, src/Utilities/Utilities.csproj
Fixes #404
The test assembly was renamed too.
Did the same for the default namespaces.
=> Added prefix ServiceBusExplorer. to assembly names

src/ServiceBusExplorer/Forms/OptionForm.Designer.cs, src/ServiceBusExplorer/Forms/OptionForm.cs
This fixes #270. 
The buttons now look like this:
The OK button now saves the values to file. The Reset button sets the parameters to their defaults.
=> Change Options form buttons

src/Common/Helpers/MessageAndPropertiesHelper.cs, src/ServiceBusExplorer/Forms/MainForm.cs
* Refactored several properties and their fields into autoproperties.
* Removed the RelayMessageText property since it was only being saved, never used.
I got into this when looking at these properties to determine where they are used to divide them into appropriate groups for the creation of tabs in the Options dialog, #403.
=> Refactored several properties and their fields in the MainForm into autoproperties.

src/Common/Helpers/ConfigurationHelper.cs, src/Common/Helpers/ConfigurationParameters.cs, src/Common/Helpers/MainSettings.cs, src/Common/Helpers/ServiceBusHelper.cs, src/ServiceBus/Helpers/ServiceBusHelper2.cs, src/ServiceBus/Helpers/ServiceBusPurger.cs, src/ServiceBusExplorer/Forms/ConnectForm.cs, src/ServiceBusExplorer/Forms/ConnectForm.designer.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Forms/OptionForm.Designer.cs, src/ServiceBusExplorer/Forms/OptionForm.cs
This PR aims to fix #396
It also replugs all the event handlers lost on the OptionForm
Amqp setting is now enabled:
Amqp settings and Connectivity mode are now taken from the options:
=> Allow configuring AMQP Web Sockets usage

App.config
This PR fixes the wrong FQDN of helper components such as message generators and message inspectors. This bug was introduced by the split of the solution into multiple projects as the helper components in question have been moved to a separate assembly and project (Common) and the namespace of these classes has been changed to ServiceBusExplorer.Helpers.
=> Fixed the FQDN of classes in the App.config

src/Common/Helpers/ConfigurationHelper.cs, src/Common/Helpers/ConfigurationParameters.cs, src/Common/Helpers/MainSettings.cs, src/ServiceBusExplorer/Controls/AccidentalDeletionPreventionCheckControl.Designer.cs, src/ServiceBusExplorer/Controls/AccidentalDeletionPreventionCheckControl.cs, src/ServiceBusExplorer/Controls/AccidentalDeletionPreventionCheckControl.resx, src/ServiceBusExplorer/Forms/DeleteForm.Designer.cs, src/ServiceBusExplorer/Forms/DeleteForm.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Forms/OptionForm.Designer.cs, src/ServiceBusExplorer/Forms/OptionForm.cs, src/ServiceBusExplorer/ServiceBusExplorer.csproj
I was recently working with our production environment with Service Bus Explorer, and an accidental Delete keystroke was sent to the tree view with the root node selected, and I realized with alarm that I was one errant mouse or key action away from completely annihilating every single Service Bus queue, topic, subscription for our production environment.
This PR adds a new feature so that if a deletion has a broad scope, the delete form prompts the user to explicitly type in what it is they want to delete. If they don't actually type the words "Absolutely Everything", for instance, then Service Bus Explorer will not in fact delete absolutely everything.
When I was first writing this, I imagined actually putting the name of the item to be deleted into the input box -- this could still be …
=> Added UI flow to reduce the likelihood of accidental mass deletions

src/Common/Helpers/ConfigurationHelper.cs, src/Common/Helpers/ConfigurationParameters.cs, src/Common/Helpers/Constants.cs, src/Common/Helpers/MainSettings.cs, src/ServiceBusExplorer.sln.DotSettings, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Forms/OptionForm.Designer.cs, src/ServiceBusExplorer/Forms/OptionForm.cs
The purpose of this PR is to allow configuring the message counts that the user wants to display.
It defaults to the current display (Active/DeadLetter/Transfer DeadLetter), but also allows to select Scheduled/Transfer message counts as well. Order is not modifiable but this should already bring some value to users.
> Note that this PR might conflict with #468 due to the modification of the same code zones. I will happily handle the merge once any will be merged into the repo
Sorry, all counts are at 0, but you can get the idea
=> Allow selection of message counts to display

src/Common/Helpers/ConfigurationHelper.cs, src/Common/Helpers/ConfigurationParameters.cs, src/Common/Helpers/MainSettings.cs, src/ServiceBusExplorer/Controls/DataGridViewColorPickerColumn.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Forms/OptionForm.Designer.cs, src/ServiceBusExplorer/Forms/OptionForm.cs, src/ServiceBusExplorer/Forms/OptionForm.resx, src/ServiceBusExplorer/ServiceBusExplorer.csproj, src/Utilities/Helpers/NodeColorInfo.cs
The purpose of this PR is to allow configuring colors for nodes (either leaves or intermediate "directories") based on regular expressions.
=> Add coloring feature to nodes

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Forms/ReceiveModeForm.Designer.cs, src/ServiceBusExplorer/Forms/ReceiveModeForm.cs, src/ServiceBusExplorer/ServiceBusExplorer.csproj
This PR implements the feature request #464 in a very minimalistic and non-invasive way.
Adds support for limiting retrieving messages to specific sessions only.
Currently only Queues are supported but Session aware Subscriptions should also work with minimal extra work.
For this I will create another small PR if this one is accepted.
I tried to touch as less code as possible to implement this.
In this version the user has to manually type in the Session ID in the dialog window for retrieving messages.
If requested a list of available messages sessions could be provided in the dialog aswell but then I would prefer to extract the dialog and implement one Session-aware dialog and one for all non-session-aware entities.
=> Feature: Retrieve queue messages from a specific session only

src/ServiceBusExplorer/Forms/MessageForm.cs
…one() for Streams
Regarding:
https://github.com/paolosalvatori/ServiceBusExplorer/issues/245
This appears to be everything necessary in order to resolve the issue I was having.
I am uncertain of all functionality of ServiceBusExplorer to QA this change, but this is basically what I found will meet the needs of properly cloning a stream.
=> fixed cloning by utilizing Service Bus .Clone(stream) instead of .Clone(string)

src/Common/Common.csproj, src/Common/Helpers/BrokeredMessageExtensions.cs, src/Common/Helpers/Constants.cs, src/Common/Helpers/IEnumerableExtensions.cs, src/ServiceBusExplorer/Forms/MessageForm.cs
Fixes #344
When resubmitting several messages in batch mode, properties should be copied when cloning. But when resubmitting only one message, properties should not, because the user can choose what properties he wants to copy through Message Custom Properties GroupBox.
So, clone depends on resubmitting one or more messages.
In any case, properties with name "DeadLetterReason", "DeadLetterErrorDescription" and "NServiceBus.Transport.Recovery", should never be copied.
Issue #344 should be solved with this PR.
=> Fix copying behavior of properties when resubmitting messages

src/ServiceBusExplorer/Forms/MainForm.Designer.cs, src/ServiceBusExplorer/Forms/MainForm.cs
Prior to this PR, when you used the Receive messages features and you used the `Enter` key to close the modal form allowing to provide details (mode, number of messages), quite frequently, immediately after receiving messages, the right tab switched back to the queue/subscription details.
Apart from the annoyance, when using Receive mode, it meant messages were lost without a way to get them anymore.
This was due to the fact that events are sent in the following order:
* `KeyDown`
* `KeyPress`
* `Keyup`
As the `KeyPress` was consumed to close the modal form, the `KeyUp` was sent to the parent window, which is often in this case the tree view, in turn resulting in its `KeyUp` event to fire.
Switching to `KeyDown` for the tree view easily solves this, and makes the behavior consistent with …
=> Prevent tab to switch after receiving messages

.gitignore, src/Common/Common.csproj.DotSettings, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj.DotSettings, src/ServiceBusExplorer.sln.DotSettings, src/ServiceBusExplorer/ServiceBusExplorer.csproj, src/ServiceBusExplorer/ServiceBusExplorer.csproj.DotSettings
I decreased some of ReSharper code inspections from _Error_ to _Warning_. I assume the configuration was created when all contributors were using ReSharper and since then developers have contributed without using ReSharper. And alternative to relaxing the code inspections would be to run them during the build.
I did not find a way to instruct ReSharper to use the C# language version specified in the `.csproj` files and instead had to create `.csproj.DotSettings` files. This does not feel right as the C# language version is now specified in two places. On the plus side I did simplify the C# language version settings in the `.csproj` files.
I ignored the Rider directory (`.rider/`). I don't know how well Rider will support working on the Service Bus Explorer code base but I was able to …
=> Fix errors displayed by Rider / ReSharper

src/ServiceBusExplorer/Controls/HandleNotificationHubControl.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.cs, src/ServiceBusExplorer/Controls/NumericTextBox.cs, src/ServiceBusExplorer/Controls/TimeSpanControl.cs
Following #493 , I introduced a regression pointed in #501 as users were forced to enter values in the `TimeSpanControl`.
This PR reintroduces the previous behavior which is to ensure that if all fields are empty or whitespace, then the default value for the property is to be used.
Sorry for this regression!
=> Make empty TimeSpanControl indicate usage of default value

src/ServiceBus/Helpers/ServiceBusHelper2.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.cs
Fixes #499 
The maximum queue length controller (slider) to reflect the maximum queue size available for the used namespace SKU.
=> Correctly reflect queue maximum size based on namespace SKU

src/ServiceBusExplorer/Forms/MainForm.cs
I have accidentally deleted queues and topics by locking computers / bringing up the task manager with the application open.
(alt-ctrl-del and then enter)
This change will save my job. :)
I know you can use ctrl-l to lock a windows machine but - "old dogs can't learn new tricks" and this habit is hard for me to break.
=> fix alt-ctrl-del interpreted as delete

src/ServiceBusExplorer/Controls/HandleQueueControl.cs
This PR fixes #545.
The root cause of the regression seems to have been #470, which removed the ability to retrieve messages from a session-enabled queue when no session was provided.
=> Fix messages not being read correctly from a session-enabled queue

src/ServiceBusExplorer/Controls/NumericTextBox.cs, src/ServiceBusExplorer/Controls/TimeSpanControl.Designer.cs
This fixes #548, and should resume same behavior as in 4.1.112:
* not entering any value in any field will lead to a null value being returned by the control, and the default value for the entity will be used
* entering a value in any field will default the unfilled ones to 0
=> Update TimeSpanControl so that if any field is filled, others are defaulted to zero

src/Common/Helpers/BrokeredMessageExtensions.cs, src/ServiceBusExplorer/Controls/TestQueueControl.cs, src/ServiceBusExplorer/Controls/TestTopicControl.cs
This will allow sending messages with empty bodies to queues and topics. It also allows resubmitting messages with bodies == null to queues and topics. 
Fixes #547
=> Allow empty and null messages 

src/ServiceBusExplorer/Forms/ConnectForm.cs
In the same vein as #422 this simply removes the check for entity specific connection strings since it is just working fine.
Fixes #560
=> Remove check for non-empty Entity Path

src/ServiceBusExplorer/UIHelpers/DictionaryPropertyDescriptor.cs
Fixes #581 
When the dictionary behind a ´DictionaryPropertyDescriptor´  contains a key for which the value is "null", the PropertyType property fails with a ´NullReferenException´.  By changing ´_dictionary[_key].GetType()´ to ´_dictionary[_key]?.GetType()´ (notice the question mark) we bypass this problem.  The ´PropertyGrid´ is capable of dealing with a null type (the row gets disabled).  This allows us to view messages which otherwise remained hidden.
=> DictionaryPropertyDescriptor bug (issue #581)

src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
This small change aims to ensure that when resubmitting messages, the entity selector will have the entity from which messages have been initially received selected as default.
In my experience, it is the most common scenario when resubmitting messages to go to the same entity (from deadletter to active queue for instance), or to a related entity, which is often close to the one where messages have been received in the selector.
=> Set default queue or subscription when resubmitting messages

appveyor.yml, src/Common/Helpers/BrokeredMessageTemplate.cs, src/Common/Helpers/MessagePropertyInfo.cs, src/Common/Helpers/MessageSerializationHelper.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs, src/ServiceBusExplorer/Controls/TestQueueControl.cs, src/ServiceBusExplorer/Forms/MessageForm.cs, src/ServiceBusExplorer/ServiceBusExplorer.csproj
Fixes #586
**Replaces #617, #623** (~~GitVersion issued due to the branch name~~, source of the branch?)
This PR is an **attempt** to fix the export/import of JSON messages.
There's a whole slew of broken things with the current code base 😞
- Serialization
- ❌ Incorrectly stored body - the body is stored as an object rather than raw JSON. To work properly, the body has to be saved as an escaped JSON string.
- ❌ Incorrectly stored properties/headers - headers are stored as an object where it should be an array of key/value objects
- Deserialization
- ❌ Incorrectly deserialized body - deserialized property is called `content` rather than `body`
- ✖️ Incorrect merging of deserialized properties/headers and custom provide via app properties/headers - properties provided via app are lost. …
=> Exported JSON cannot be imported

src/Common/Helpers/ServiceBusHelper.cs
When a message property 'Content-Encoding' is added to the message, with value 'gzip', support decompressing the body content to see the uncompressed payload.
=> Support gzip compressed messages

src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
Fixes null reference exception when creating a new subscription, introduced by commit 09aa1eb5d1b1606935a08dc03f0f071e5508018c .
=> Fix null ref creating new subscription

src/Common/Helpers/ServiceBusHelper.cs, src/ServiceBusExplorer.Tests/Helpers/ServiceBusHelperTest.cs
Currently, relative urls for subscriptions forwards for example, are checked by ensuring the uri of the namespace is a base of the subscription url, before getting the relative path.
When the url is not absolute, or the condition above is false, the code fallbacks to a simple and imperfect string parsing code.
Recently, it has been put to my knowledge that some tooling where using different schemes for the urls (in this case, MassTransit uses `http://` rather than `sb://`).
This has no impact on the actual behavior of the service bus.
As such, I propose this PR to ensure the scheme is ignored when doing this matching, by copying the scheme of the namespace to the compared uri.
For technical purposes, I had to copy the port from the namespace also to prevent a default port to be added the …
=> Support inconsistent schemes that have no impacts on actual behavior

src/Common/Common.csproj, src/EventHubs/EventHubs.csproj, src/NotificationHubs/NotificationHubs.csproj, src/ServiceBus/ServiceBus.csproj, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer/App.config, src/ServiceBusExplorer/ServiceBusExplorer.csproj, src/Utilities/Utilities.csproj
This required updating app.config so users should only keep the connections section and other customized sections in the servicebusexplorer.exe.config when upgrading.
=> Updated NuGet packages

.github/workflows/build-test.yml
The NuGet package NUnit.ConsoleRunner does not contain the extensions that are included in the MSI package NUnit.Console. There is a great comment about this at https://github.com/nunit/docs/issues/311#issuecomment-494573236. 
One of the solutions for this is to install the NuGet package NUnit.Extension.VSProjectLoader. It is not a .NET tool package though so I am sticking with Install-Package.
=> Adding installation of vs-project extension to solve NUnit issue

.github/stale.yml
Currently an issue is closed after 60 days by the bot. We want to keep issues that have been labeled as bug, feature and some other labels to be permanent.
=> Keep more issues from getting closed

src/Common/Properties/AssemblyInfo.cs, src/NotificationHubs/Properties/AssemblyInfo.cs, src/ServiceBusExplorer.Tests/Properties/AssemblyInfo.cs
Set file version to 0.0.0.0 in the .NET Framework projects to make it clear that it is not used.
=> Set file version to 0.0.0.0 in the .NET Framework projects.

src/Common/Helpers/MessageAndPropertiesHelper.cs
Currently the settings cannot be saved on a fresh install of 5.0.10 because of the NullReferenceException thrown on line 670 of `OptionForm` for `ConfigurationParameters.MessageParameter`.
```System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=ServiceBusExplorer
StackTrace:
at ServiceBusExplorer.Forms.OptionForm.SaveSetting[T](TwoFilesConfiguration configuration, MainSettings savedSettings, String setting, T runningValue) in C:\Users\AWITKOWS\source\repos\ServiceBusExplorer\src\ServiceBusExplorer\Forms\OptionForm.cs:line 670
at ServiceBusExplorer.Forms.OptionForm.SaveSettings(ConfigFileUse configFileUse) in C:\Users\AWITKOWS\source\repos\ServiceBusExplorer\src\ServiceBusExplorer\Forms\OptionForm.cs:line 622
at …
```
=> If the message file does not exist, make the messageText an empty string (instead of null)

src/Common/Helpers/ServiceBusHelper.cs, src/EventHubs/EventHubs.csproj, src/ServiceBus/Helpers/ServiceBusHelper2.cs, src/ServiceBus/ServiceBus.csproj, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.cs
Fixes #611
The EntityPath was previously removed from the connection string, since the Track 0 SDK cannot handle it. However, Track 2 SDK requires it. This PR preserves the original string.
The ConnectionStringContainsEntityPath method could have been put inside the IsPremiumNamespace method but having it outside makes it clearer that this is sort of a hack. To get a good solution I'd prefer to have an enum for the SKU, where one of the enum members should be "unknown" since it looks like we won't be able to get the SKU when using a connection string containing an EntityPath. In that case some parts of the GUI should be hidden.
But let's start with this and make sure it works.
=> Fix the ability to connect using an EntityPath connection string

.github/workflows/build-test.yml, .github/workflows/handle-tag.yml, .github/workflows/publish.yml, GetNumberVersion.ps1, SetVersion.ps1
Fixes #697 
Since Assembly version and file version don't allow letters this PR adds setting the Informational file version, which allows letters. Then we can have 5.3.4-beta1.
=> Support preview releases

src/ServiceBusExplorer/Forms/MainForm.cs
Fix for Issue [702](https://github.com/paolosalvatori/ServiceBusExplorer/issues/702).
Modify subscriptionsExtractor  anonymous function so that it handles the case where tn.FirstNode is null by returning an empty Enumerable.
=> Modify BulkPurge to handle Topic with no Subscriptions

src/ServiceBusExplorer.Tests/Helpers/ServiceBusHelperTest.cs, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer.sln.DotSettings, src/ServiceBusExplorer/Controls/HandleQueueControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.resx, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.resx, src/ServiceBusExplorer/Controls/ListenerControl.Designer.cs, src/ServiceBusExplorer/Controls/ListenerControl.cs, src/ServiceBusExplorer/Controls/ListenerControl.resx
I found out that the issue discussed in #712 only occurs when Azure.Messaging.ServiceBus is used.
I added UnitTest to show that the issue does not occur if you use Windows.AzureService.
I failed to reproduce exactly the error. I added a test that somehow emulates the error behavior. I do have not enough knowledge of what was changed between the two APIs. Also, the current Protobuf Nuget Package does not support 4.6.2 so i had to add the Protobuf message as a byte array :(
I ended up adding an additional menu item to resubmit a single message without changing the content.
I reused the code from the resubmit of multiple messages.
But that is just a workaround.
I manually tested re-submitting in Azure ServiceBus Queue and Topic and in both cases DLQ-Messages.
I was not able to manually test …
=> Re-submit a single message with binary content created with Azure.Messaging.ServiceBus nuget package

.github/workflows/publish.yml, .gitignore
GitHub Actions was unable to upload the package to chocolatey. The error message is: 
> "Default push source configuration is not set. Please pass a source to push to, such as --source=https://push.chocolatey.org/"
Adding --source=https://push.chocolatey.org/ should put the package in the community feed, where it is located today.
As to the reason this happened my guess is the VM used for the build is using a newer version of choco that requires this parameter.
=> Add source configuration to choco push command

src/Common/Abstractions/EventDataMessage.cs, src/Common/Helpers/ServiceBusHelper.cs, src/ServiceBus/Helpers/ServiceBusPurger.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.cs, src/ServiceBusExplorer/Controls/PartitionListenerControl.cs, src/ServiceBusExplorer/Forms/EventDataForm.cs, src/ServiceBusExplorer/UIHelpers/LanguageDetector.cs
Fixes #720 #738 #638 
A breaking change was introduced in the track 0 SDK `WindowsAzure.ServiceBus` somewhere after version `6.0.3`. As a result of that, it broke SBE ability to clone EventHub messages for UI purposes. This PR is a workaround for the issue to allow rendering EH messages, its custom and system properties, w/o throwing exceptions.
https://github.com/paolosalvatori/ServiceBusExplorer/assets/1309622/95ebead3-8968-403c-b5b6-30ce443253c5
Disclaimer: I have not tested all the permutations of what can be done with EH. I would appreciate it if someone could take a look to see if there are any undesirable side effects. This is merely an attempt to unblock those who need to be able to list and evaluate messages sent to EH.
=> Abstracting EventHubs EventData

src/EventGridExplorerLibrary/EventGridLibrary.cs
The tenantId field was always null when calling InteractiveBrowserCredential. This seems to work with work accounts but not personal Microsoft accounts. 
This PR sets the tenantId to the custom tenantId, if it is specified.
=> Change the way the tenantId is used in the Event Grid login

src/ServiceBusExplorer/Forms/MainForm.Designer.cs
It now looks like this again:
Seems that these changes were lost when another PR was merged.
Fixes #760
=> Put back the submenus for Set Status

src/Common/Helpers/DeadLetterMessageHandler.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.resx, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs, src/ServiceBusExplorer/Forms/MessageForm.cs, src/ServiceBusExplorer/UIHelpers/DataGridViewHelper.cs
Before this PR the context menu when selecting a single Transfer DLQ message looks like this:
and when selecting multiple messages it looks like this:
This PR removes the separate handling of the Transfer Deadletter context menus, they are now the same as for the Deadletter context menus. A lot of the code for handling messages in these subqueues is now shared. 
Also added the feature to selectively delete Transfer deadletter messages.
The above is only added for queues and not for subscriptions as the transfer deadletter support is a bit mysterious for subscriptions.
=> Add selective delete to Transfer deadletter subqueues and fix the context menus for the Transfer Deadletter grid view

src/Common/Helpers/ServiceBusHelper.cs, src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs, src/ServiceBus/Helpers/ServiceBusHelper2.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.Designer.cs, src/ServiceBusExplorer/Controls/HandleQueueControl.cs
Fixes #360
This PR adds the ability to cancel scheduled messages on queues. The Service bus API does not support browsing scheduled messages on subscriptions. 
A new context menu item "Cancel Scheduled Message" has been added as shown below:
If multiple messages are selected it says "Cancel Scheduled Messages" instead:
If the _Disable Accidental Deletion Prevention_ is disabled, a message box will ask for confirmation. 
The rows in the grid will not update, nor will the message count for the queue in the tree view. That is something that may be added later.
=> Add the ability to cancel scheduled messages

src/Common/Helpers/ConfigurationHelper.cs, src/ServiceBusExplorer/App.config, src/ServiceBusExplorer/Forms/ConnectForm.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Program.cs
Fixes #769 
Shows one or two error messages if a config file is incorrect. The application still dies after that.
=> Show error message if a config file is incorrect

src/ServiceBusExplorer/Forms/MessageForm.cs
Fixes #633 
This PR changes the reading of messages of type string to be read using GetBody\<string>() instead of GetBody\<Stream>(), thus avoiding getting unwanted text in the message. 
Also did an auto format which changed some whitespace.
Thanks to @Anshuljkt for his work on #764, which helped in creating this PR and to @Flower7434 for the tip about reading messages.
=> Fix Submit batch for messages of type string

.github/workflows/build-test.yml
We are getting a build warning about two GitHub actions being deprectated. This PR upgrades them to supported versions.
=> Updated to supported versions of github actions

src/Common/Helpers/TwoFilesConfiguration.cs
Default to use the config file in the user profile directory instead of the application directory. 
Fixes #621
=> Default to use the config file in user profile

.github/workflows/handle-tag.yml, .github/workflows/winget-submission.yml
This is intended to publish the SBE package to WinGet during the release process.
=> Add publishing to winget

src/Common/Common.csproj, src/Common/app.config, src/NotificationHubs/NotificationHubs.csproj, src/NotificationHubs/app.config, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer.Tests/app.config, src/ServiceBusExplorer/App.config, src/ServiceBusExplorer/Controls/Grouper.cs, src/ServiceBusExplorer/Controls/HandleTopicControl.cs, src/ServiceBusExplorer/Controls/HeaderPanel.cs, src/ServiceBusExplorer/Forms/ChangeStatusForm.cs, src/ServiceBusExplorer/Forms/ClipboardForm.cs, src/ServiceBusExplorer/Forms/ConnectForm.cs, src/ServiceBusExplorer/Forms/ConnectForm.designer.cs, src/ServiceBusExplorer/Forms/DeleteForm.Designer.cs, src/ServiceBusExplorer/Forms/DeleteForm.cs, src/ServiceBusExplorer/Forms/FilterForm.cs, src/ServiceBusExplorer/Forms/MainForm.cs, src/ServiceBusExplorer/Forms/NewVersionAvailableForm.Designer.cs, src/ServiceBusExplorer/Forms/NewVersionAvailableForm.cs, src/ServiceBusExplorer/Forms/ParameterForm.cs, src/ServiceBusExplorer/ServiceBusExplorer.csproj, src/ServiceBusExplorer/UIHelpers/ControlHelper.cs, src/ServiceBusExplorer/app.manifest, src/Utilities/Helpers/GitHubReleaseProvider.cs
* Adding support for .NET Framework 4.7.2 and using the settings in the app.manifest file for enabling high DPI support, and for taking advantage of some new helper methods the framework offers for high DPI related calculations, such as LogicalToDeviceUnits and ScaleBitmapLogicalToDevice
* Changes for making the ConnectForm and MainForm work with high DPI, by fixing how the height of some controls are calculated, such as HeaderPanel or HandleTopicControl.
* Whitespace formatting in the FilterForm.
* Fixes for the message dialogs ChangeStatusForm, ClipboardForm and DeleteForm, so the message text is displayed completely. 
* Changes in the ParameterForm and the MainForm to display the ParameterForm properly in high DPI.
* Changes in the NewVersionAvailableForm, for showing the labels …
=> First set changes to enable high DPI in Service Bus Explorer

src/ServiceBusExplorer/Program.cs
This happens if the user configuration contains invalid XML, for instance.
=> Show error message when a fatal error occurs

src/Common/Helpers/ImportExportHelper.cs
In the current version, when exporting topics, the eventual properties of the CorrelationFilter of a subscription is not exported, nor imporetd
This pull requesrt correct this
=> Export/Import Properties of CorrelationFilter

src/Common/Helpers/ServiceBusNamespace.cs
If a connection string ends with a ";" semi colon the split function returns an empty string as the last entry causing an exception.
By removing those empty entries, exception can be avoided, and application works as expected.
=> fixes an issue when connection string ending with ";" causes an exception

src/ServiceBusExplorer/Forms/MainForm.cs
Fixes #802 
just implement the feature when refresh the topic node.
not sure is it necessary to implement at other mode(Queues, Eventhhubs), as their Treeview structure was different.
not keep subscription node and rule node expaned, as it will add some ugly compare code in Foreach cycle and in daily use I just want keep subscriptions node expaned.
=> Implement issue 802

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusQueue.cs, src/Common/WindowsAzure/ServiceBusQueue.cs
First part of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes, and to set-up a basic structure of classes.
This part is moving Queue 'management actions' - that is, actions for Queues that need the `Microsoft.ServiceBus.NamespaceManager` to work.
=> #686: Move Queue management functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusEntity.cs, src/Common/WindowsAzure/IServiceBusQueue.cs, src/Common/WindowsAzure/IServiceBusTopic.cs, src/Common/WindowsAzure/ServiceBusEntity.cs, src/Common/WindowsAzure/ServiceBusQueue.cs, src/Common/WindowsAzure/ServiceBusTopic.cs
Part 02 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.
This part is moving Topic 'management actions' - that is, actions for Topics that need the `Microsoft.ServiceBus.NamespaceManager` to work.
In addition:
- Added a base class `ServiceBusEntity` to share some code between Queue and Topic implementations.
- Changed two properties in `ServiceBusHelper` to have a `private set` to indicate it is not set from outside the class.
=> #686: Move Topic management functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusSubscription.cs, src/Common/WindowsAzure/ServiceBusEntity.cs, src/Common/WindowsAzure/ServiceBusSubscription.cs
Part 03 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.
This part is moving Subscription 'management actions' - that is, actions for Subscriptions that need the Microsoft.ServiceBus.NamespaceManager to work.
In addition:
- Add a general OnCreated() method because some Subscription events use a custom type `SubscriptionWrapper` for  `ServiceBusHelperEventArgs.EntityInstance`, which in turn is used in various UI Controls
=> #686: Move Subscription management functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusRule.cs, src/Common/WindowsAzure/ServiceBusEntity.cs, src/Common/WindowsAzure/ServiceBusRule.cs
Part 04 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.
This part is moving Rules 'management actions' - that is, actions for Rules that need the `Microsoft.ServiceBus.NamespaceManager` to work, or add/remove actions on Rules which can only be done via `MessagingFactory`.
In addition:
* Add a general OnDeleted() method because some Rule events use a custom type `RuleWrapper` for `ServiceBusHelperEventArgs.EntityInstance`, which in turn is used in various UI Controls
=> #686: Move Rule management functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusNotificationHub.cs, src/Common/WindowsAzure/ServiceBusNotificationHub.cs
Part 06 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.
This part is moving NotificationHub 'management actions' - that is, actions for NotificationHubs that need the `Microsoft.Azure.NotificationHubs.NamespaceManager` to work. 
NotificationHub uses a different (dedicated) SDK, but it is still put in the same structure as the other types for the first-pass of this.
=> #686: Move NotificationHub management functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusEventHub.cs, src/Common/WindowsAzure/ServiceBusEventHub.cs
Part 07 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.
This part is moving EventHub 'management actions' - that is, actions for EventHubs that need the `Microsoft.ServiceBus.NamespaceManager` to work.
=> #686: Move EventHub management functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusConsumerGroup.cs, src/Common/WindowsAzure/ServiceBusConsumerGroup.cs
Part 08 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.
This part is moving ConsumerGroup 'management actions' - that is, actions for ConsumerGroups that need the `Microsoft.ServiceBus.NamespaceManager` to work.
=> #686: Move ConsumerGroup management functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusPartition.cs, src/Common/WindowsAzure/ServiceBusPartition.cs
Part 09 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.
This part is moving Partition 'retrieval actions' - that is, actions for Partitions (from EventHub) that need the `Microsoft.ServiceBus.NamespaceManager` to work.
=> #686: Move Partition retrieval functions to separate class

src/Common/Helpers/ServiceBusHelper.cs, src/Common/WindowsAzure/IServiceBusConsumerGroup.cs, src/Common/WindowsAzure/IServiceBusEventHub.cs, src/Common/WindowsAzure/IServiceBusNotificationHub.cs, src/Common/WindowsAzure/IServiceBusPartition.cs, src/Common/WindowsAzure/IServiceBusQueue.cs, src/Common/WindowsAzure/IServiceBusRule.cs, src/Common/WindowsAzure/IServiceBusSubscription.cs, src/Common/WindowsAzure/IServiceBusTopic.cs, src/Common/WindowsAzure/ServiceBusConsumerGroup.cs, src/Common/WindowsAzure/ServiceBusEventHub.cs, src/Common/WindowsAzure/ServiceBusNotificationHub.cs, src/Common/WindowsAzure/ServiceBusPartition.cs, src/Common/WindowsAzure/ServiceBusQueue.cs, src/Common/WindowsAzure/ServiceBusRule.cs, src/Common/WindowsAzure/ServiceBusSubscription.cs, src/Common/WindowsAzure/ServiceBusTopic.cs
Part 10 of refactoring the `ServiceBusHelper` class #686. This is a 'code cleanup' where unused code in `ServiceBusHelper` (and in the related WindowsAzure.ServiceBus* files) is removed, and a few methods are changed from `public` to `private` since there was no usage outside the class.
=> #686: Remove unused code and make some methods private

README.md
Closes #455 
This pull request updates the `README.md` file to include instructions for installing the Service Bus Explorer using Winget, providing an additional installation option for users.
Documentation Updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R60-R65): Added a new section titled "Using Winget" with installation instructions for Service Bus Explorer via the Winget package manager.
=> docs: adding possibility to install from winget

.github/workflows/build-test.yml, src/ServiceBusExplorer.sln
actions/cache@v3.0.11 is not working anymore. Therefore upgraded it. For more information, see https://github.com/actions/cache/discussions/1510.
=> Update actions/cache to v4

.github/workflows/winget-submission.yml, src/Common/Common.csproj, src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj, src/EventHubs/EventHubs.csproj, src/NotificationHubs/NotificationHubs.csproj, src/Relay/Relay.csproj, src/ServiceBus/ServiceBus.csproj, src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj, src/ServiceBusExplorer/ServiceBusExplorer.csproj, src/Utilities/Utilities.csproj
There was a regression bug that stopped preview builds. This should enable it. 
Also sneaked in a minor change to the GitHub Workflows that publishes the package to WinGet. This will still not make it work though.
=> Enable preview builds again

src/ServiceBusExplorer/Forms/SelectEntityForm.cs
Uses node.Name for selecting entity when resubmitting a message.
=> Fix selecting queues when they are filtered
