paolosalvatori/ServiceBusExplorer

- Forms/MessageForm.cs
Handle null Message Property values when re-submitting deadletter messages
> Handle null Message Property values when re-submitting deadletter msg

- Controls/HandleQueueControl.cs
- Helpers/ServiceBusHelper.cs
I'm trying to think of a way that would allow all NServiceBus users on ASB to use SB Explorer. 
NSB is using UTF8 encoded messages with BOM, stored as byte array.
> Support byte array body (NServiceBus like messages)

- Controls/HandleQueueControl.cs
- Controls/HandleTopicControl.cs
- Forms/MainForm.cs
The following actions are added:
- Allow to select an entity from the treeview by pressing `enter` key
- Purge queue messages with Shift-Delete key press
> Keyboard operations

- Forms/MainForm.cs
fixes https://github.com/paolosalvatori/ServiceBusExplorer/issues/3
> Refresh individual topic or subscription with F5

- ServiceBusExplorer.Setup/ServiceBusExplorer.Setup.vdproj
- ServiceBusExplorer.sln
Added a setup project so that service bus explorer can be installed on desired machines as opposed to pulling down the project when needing to use the application.
> Added installation project

- ServiceBusExplorer.csproj
- packages.config
Fixed #46 
@paolosalvatori please merge
> Support for BrokeredMessage.DeadLetterSource

- Controls/HandleQueueControl.cs
- Controls/HandleSubscriptionControl.cs
A maximum of 250 messages were being peeked when viewing the deadletter messages from a queue or subscription. This change uses the looping approach used elsewhere in SBE to continue until the requested count has been peeked.
> Keep peeking queue and subscription deadletter messages until the requested count has been peeked.

- Forms/MessageForm.Designer.cs
- Forms/MessageForm.cs
- Helpers/BrokeredMessageExtensions.cs
- Helpers/ServiceBusHelper.cs
> Allow to resubmit a message with ByteArray body type

- appveyor.yml
Connects to #2 
This will deploy a zip file to GH releases.
@paolosalvatori need to be able to create a deployment token on GH.
Looks like I don't have permissions.
> CI to deploy to GH

- Forms/AboutForm.Designer.cs
- Forms/MainForm.Designer.cs
- Helpers/VersionProvider.cs
- Properties/AssemblyInfo.cs
- ServiceBusExplorer.csproj
- appveyor.yml
Using AppVeyor.yml to patch AssemblyInfo file with the right version
> Package version number using AppVeyor config file

- App.config
- Helpers/VersionProvider.cs
- Properties/AssemblyInfo.cs
- ServiceBusExplorer.Tests/app.config
- ServiceBusExplorer.csproj
- packages.config
> Implement GitVersionTask for determining product version

- Controls/HandleQueueControl.cs
- Controls/HandleSubscriptionControl.cs
> Confirm purge operation

- Controls/HandleQueueControl.Designer.cs
- Controls/HandleQueueControl.cs
- Forms/MainForm.cs
> [WIP] initial commit for transfer dlq messages

- Forms/AboutForm.Designer.cs
- Forms/MainForm.Designer.cs
- Helpers/VersionProvider.cs
- ServiceBusExplorer.sln
- appveyor.yml
> Fixing build number

- appveyor.yml
> Embed version in zip filename

- src/ServiceBusExplorer/App.config
This pull request fixes the configuration file
> Fixed app.config

- README.md
- appveyor.yml
Relates to #137 and cleans up #147
> Only push choc packages from master with flexible version

- src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
- src/ServiceBusExplorer/Forms/MainForm.cs
- src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs
Connects to #149 that handled queues and topics.
> Handle subscriptions deletions in async manner

- src/ServiceBusExplorer/Controls/CheckBoxComboBox.cs
- src/ServiceBusExplorer/Controls/DataGridViewDateTimePickerColumn.cs
- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
- src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
- src/ServiceBusExplorer/Controls/ListenerControl.cs
- src/ServiceBusExplorer/Controls/PartitionListenerControl.cs
- src/ServiceBusExplorer/Controls/TestEventHubControl.cs
- src/ServiceBusExplorer/Controls/TestQueueControl.cs
- src/ServiceBusExplorer/Controls/TestRelayControl.cs
- src/ServiceBusExplorer/Controls/TestSubscriptionControl.cs
- src/ServiceBusExplorer/Controls/TestTopicControl.cs
- src/ServiceBusExplorer/Controls/TrackBar.cs
- src/ServiceBusExplorer/Forms/ConnectForm.cs
- src/ServiceBusExplorer/Forms/ContainerForm.cs
- src/ServiceBusExplorer/Forms/EventDataForm.cs
- src/ServiceBusExplorer/Forms/FilterForm.cs
- src/ServiceBusExplorer/Forms/MainForm.cs
- src/ServiceBusExplorer/Forms/MessageForm.cs
- src/ServiceBusExplorer/Forms/OptionForm.cs
- src/ServiceBusExplorer/Forms/ReceiveModeForm.cs
- src/ServiceBusExplorer/Forms/RegistrationsForm.cs
- src/ServiceBusExplorer/Helpers/CustomObject.cs
- src/ServiceBusExplorer/Helpers/CustomPropertyDescriptor.cs
- src/ServiceBusExplorer/Helpers/ImportExportHelper.cs
- src/ServiceBusExplorer/Helpers/JsonTimestampHelper.cs
- src/ServiceBusExplorer/Helpers/MetricHelper.cs
- src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs
- src/ServiceBusExplorer/Helpers/SimpleSite.cs
- src/ServiceBusExplorer/Helpers/SortableBindingList.cs
- src/ServiceBusExplorer/Helpers/StandardValuesConverter.cs
Based on top of #150 
C# cleanups to remove noise
> C#7 cleanups

- README.md
Related to #157.
It is very basic but I think it covers most of the relevant information.
-------------
@SeanFeldman you mentioned the following:
> fixed issues/PRs should be assigned the next release milestone upon completion
Not sure if this is related for contributions as this is more for the maintainers?
> Add basic contribution information

- src/ServiceBusExplorer/Forms/ConnectForm.cs
- src/ServiceBusExplorer/Forms/ConnectForm.designer.cs
- src/ServiceBusExplorer/Helpers/ServiceBusNamespace.cs
This is a follow up bug fix which is related to #168 EntityPath changes.
* When saving the connection string with an EntityPath the connection string was not parsed
* There was no UI support for EntityPath
* When saving a connection string the combo box had the select and add connection string options removed which caused problems with selecting the connection strings
I've added a new textbox to allow the EntityPath to be viewed and fixed the other issues.
> Bug fix related to #168

- VERIFICATION-Template.txt
> Add MD5 as checksum type in template

- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
- src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
- src/ServiceBusExplorer/Helpers/ServiceBusNamespace.cs
- unnecessary initializations
- XML documentation that was omitted from PR #168
@paolosalvatori please review/merge
> minor cleanups

- src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
- src/ServiceBusExplorer.sln
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
> Cnabling 7.x C# features

- src/ServiceBusExplorer/Forms/ConnectForm.designer.cs
Fixes #187 
@paolosalvatori can you merge this? Thanks.
> Bring develop on par with master

- src/ServiceBusExplorer/Forms/MainForm.cs
- src/ServiceBusExplorer/Forms/MessageForm.cs
Fixes #205 
I'm not entirely sure on the syntax in the messages for Relays, Notification Hubs, and EventHubs.
> Show exception when entities cannot be retrieved

- src/ServiceBusExplorer/Helpers/ServiceBusHelper.cs
Check host is contactable before progressing to give user quicker feedback. Also we don't need to retry if it's not a real host.
Fixes issue #209
> Test host is resolvable before trying to connect

- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> Fix the deleting dlq message issue 

- src/ServiceBusExplorer/Controls/TestQueueControl.cs
- src/ServiceBusExplorer/Controls/TestTopicControl.cs
- src/ServiceBusExplorer/Forms/MainForm.cs
- src/ServiceBusExplorer/Forms/MessageForm.cs
- src/ServiceBusExplorer/Forms/OptionForm.Designer.cs
- src/ServiceBusExplorer/Forms/OptionForm.cs
- src/ServiceBusExplorer/Helpers/ConfigurationParameters.cs
Feature is a choiceable default MessageBodyType it is now configurable and selectable via the options dialog.
Relates to #243
> Make default message body type configurable

- src/ServiceBusExplorer/Controls/HandleRuleControl.Designer.cs
- src/ServiceBusExplorer/Controls/HandleRuleControl.cs
- src/ServiceBusExplorer/Helpers/UserPropertyWrapper.cs
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
> add support for correlation filters

- App.config
- src/ServiceBusExplorer/App.config
- src/ServiceBusExplorer/Program.cs
> Programmatically set connection limit instead of using configure

- src/ServiceBusExplorer/Program.cs
As requested , update the limit to 200 for supporting possible performance testing
> updated to 200

- src/ServiceBusExplorer/Forms/OptionForm.Designer.cs
This is the same style as most of the other dialog windows. Fixes #269.
> Made all of the background blue on the Options window

- src/ServiceBusExplorer/Controls/HandleRuleControl.Designer.cs
#271
Turned off AutoScaling and adjusted Filter Type and Default content areas.
> FixForDpiScalingInSubscriptionRules

- src/ServiceBusExplorer/Forms/MessageForm.Designer.cs
- src/ServiceBusExplorer/Forms/MessageForm.cs
> GUI change for submitting messages in batch mode 

- src/ServiceBusExplorer.Tests/Helpers/JsonSerializerHelperTest.cs
- src/ServiceBusExplorer.sln.DotSettings
- src/ServiceBusExplorer/Forms/EventDataForm.cs
- src/ServiceBusExplorer/Forms/MessageForm.cs
- src/ServiceBusExplorer/Helpers/JsonSerializerHelper.cs
- src/ServiceBusExplorer/Helpers/LanguageDetector.cs
Fixes for issue "Errors when body is empty #310"
> Fix bug when body is empty or null

- README.md
- docs/documentation.md
Just a couple typo fixes in the doco files.
> Fix a couple typos in docs

- src/ServiceBusExplorer/Forms/MainForm.cs
Fix #390 
Refresh subscription does not clear previously deleted rules
> Fix Refresh subscription does not clear previously deleted rules

- src/Common/Helpers/ImportExportHelper.cs
This PR replaces #395 implemented by @androdd. The reason for me implementing it is that there was a major restructuring in PR #381 that caused this PR to get some merge conflicts.
> Import Topic with CorrelationId Rules throws exception 

- src/ServiceBusExplorer/CommandLineOptions.cs
> Fixed bug!

- src/ServiceBusExplorer.Tests/Helpers/JsonSerializerHelperTest.cs
- src/Utilities/Helpers/JsonSerializerHelper.cs
> Fix for issue 425. Displays the original json if it is malformed.

- src/ServiceBusExplorer/Forms/OptionForm.Designer.cs
- src/ServiceBusExplorer/Forms/OptionForm.cs
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
- src/ServiceBusExplorer/UIHelpers/TabControlHelper.cs
This fixes #403. It also adds a new setting to the options dialog for setting AMQP Web Sockets. Since there isn't support for that yet it is disabled for now.
The screenshots:
> Put tabs on the Options dialog

- src/Common/Helpers/ConfigurationHelper.cs
- src/Common/Helpers/ConfigurationParameters.cs
- src/Common/Helpers/MainSettings.cs
- src/ServiceBusExplorer/Forms/MainForm.cs
- src/ServiceBusExplorer/Forms/OptionForm.Designer.cs
- src/ServiceBusExplorer/Forms/OptionForm.cs
This PR is a proposal aiming to solve the issue #343 
Rework of #430 with tabs merged since then.
> Add proxy configuration UI and logic

- src/ServiceBusExplorer/Forms/MessageForm.cs
Hi. Just a minor fix from some typos I found when using this tool.
> Fix typos.

- src/Common/Common.csproj
- src/Common/packages.config
- src/NotificationHubs/NotificationHubs.csproj
- src/NotificationHubs/packages.config
- src/ServiceBusExplorer/Forms/MainForm.cs
- src/ServiceBusExplorer/Forms/OptionForm.Designer.cs
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
Fixes #397 
Switched from Microsoft.Azure.NotificationHubs v2.16.0.234 to v1.0.9 after input from Notification Hubs product group. This is in the issue #397.
There are changes in this that come from the two previous PRs I just created.
> Change to notification hubs v1.0.9

- src/ServiceBusExplorer/Forms/MainForm.cs
- src/ServiceBusExplorer/Forms/OptionForm.Designer.cs
This should fix #447 
The changes in OptionsForm were necessary to be able to test this. Those changes are part of #446.
> Fix setting proxy error

- src/ServiceBusExplorer/Forms/OptionForm.Designer.cs
This should fix #444 
Also changed the default for the checkbox for override proxy settings to unchecked.
UI now looks like this
> Updated UI for the Options dialog

- appveyor.yml
Switch from building using Visual Studio 2017 to 2019.
> Updated appveyor.yml to use Visual Studio 2019

- App.config
Fixes #420 
Increased server and receive timeouts. Made a compromise for the setting for receive timeout according to the discussion for the issue #420.
> Increase two default timeouts

- App.config
- src/Common/Helpers/ServiceBusHelper.cs
- src/Common/Helpers/ServiceBusNamespace.cs
- src/ServiceBusExplorer/App.config
- src/ServiceBusExplorer/Controls/HandleNotificationHubControl.cs
- src/ServiceBusExplorer/Controls/TestRelayControl.cs
- src/ServiceBusExplorer/Forms/ConnectForm.cs
- src/ServiceBusExplorer/Forms/ConnectForm.designer.cs
- src/ServiceBusExplorer/Forms/ConnectForm.resx
Removed support for ACS authentication including using IssuerName. 
This fixes #262
> Removed support for ACS authentication 

- src/ServiceBusExplorer/Forms/MainForm.cs
This PR ensures that subscription nodes can benefit from the coloring feature added previously.
This is something I missed in the original development.
> Fix coloring of subscription nodes

- src/Common/Helpers/DeadLetterMessageHandler.cs
- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
- src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
- src/ServiceBusExplorer/Forms/ReceiveModeForm.cs
Refactored code to eliminate the following warnings due to non-nullable reference types in C# 8.0
CS8604
CS8602
CS8625
CS8600
CS8625
CS8619
> Refactored code to eliminate the following warnings due to non-nullable reference types in C# 8.0

- src/ServiceBusExplorer/Forms/MessageForm.cs
This fixes #492 while still retaining the original messages when reubmitting in Batch mode.
> Fix for resubmit and repair a message

- src/Common/Common.csproj
- src/Common/app.config
- src/Common/packages.config
- src/NotificationHubs/NotificationHubs.csproj
- src/NotificationHubs/packages.config
- src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
- src/Utilities/Utilities.csproj
* Updated some NuGet packages including WindowsAzure.ServiceBus
* Removed Microsoft.WindowsAzure.ConfigurationManager
* Fixed the warning about App.Config when building
* GitVersionTask is deprecated even though I updated it to the latest version.
> Updated some NuGet packages

- src/ServiceBusExplorer/Controls/TestQueueControl.Designer.cs
- src/ServiceBusExplorer/Controls/TestQueueControl.cs
- src/ServiceBusExplorer/Controls/TestTopicControl.Designer.cs
- src/ServiceBusExplorer/Controls/TestTopicControl.cs
This fixes the initial issue in  #431 by skipping the test for an empty message text and adding an explanation to the GUI that you have to change the Message Count if you want to all of the selected files if you have selected multiple files.
> Fix sending files

- src/ServiceBusExplorer/ServiceBusExplorer.csproj
- src/ServiceBusExplorer/ServiceBusExplorer.nuspec
Changed icon url in nuget.spec and added nuget.spec to the main project
> Changed icon url in nuget.spec

- src/ServiceBusExplorer/Forms/MainForm.cs
This brings more visibility when working with mulitple ASB connections at the same time.
Closes #523
> Changes the main window's text/title to ASB namespace.

- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
- src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
- src/ServiceBusExplorer/Controls/TestQueueControl.cs
- src/ServiceBusExplorer/Controls/TestSubscriptionControl.cs
- src/ServiceBusExplorer/Controls/TestTopicControl.cs
- src/ServiceBusExplorer/Forms/MainForm.cs
Hello,
I'm dealing with a SB connection where we do not have access to list subscriptions or topics.
This doesn't really work, but an initial hurdle is that establishing the connection (specifically listing the subscriptions and "event hubs") seems to get into some kind of deadlock. At least now I get an exception.
> Log exception when listing entities in the namespace

- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> Fixed queue message purge

- README.md
This PR contains some minor updates to the readme.
> Minor updates to the readme file

- src/ServiceBusExplorer/Forms/MainForm.Designer.cs
This fixes #572 by keeping the highlight on the focus node. It is very light on my screen though.
> Set the HideFocus property to false

- src/Common/Helpers/DeflateEventDataInspector.cs
- src/ServiceBusExplorer/App.config
Add the support of Deflate compression algorithm in the data inspection #sefidooza
> Add the support of Deflate compression algorithm in the data inspection

- README.md
> Added location after choco installation

- src/Common/Common.csproj
- src/EventHubs/EventHubs.csproj
- src/ServiceBus/ServiceBus.csproj
- src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
Updated the main NuGet packages to their latest versions. 
If we have extreme luck this fixes #590.
> Upated NuGet packages

- README.md
Available here: https://github.com/telstrapurple/PurpleExplorer
Related to #601
> Add Purple Explorer as an alternative tool

- src/ServiceBusExplorer/Controls/TestControlBase.cs
- src/ServiceBusExplorer/Controls/TestEventHubControl.cs
- src/ServiceBusExplorer/Controls/TestQueueControl.cs
- src/ServiceBusExplorer/Controls/TestRelayControl.cs
- src/ServiceBusExplorer/Controls/TestSubscriptionControl.cs
- src/ServiceBusExplorer/Controls/TestTopicControl.cs
Fixes #588, about the "Hi Mate..." that could not be changed.
Added a new class that is used a a base class for the classes used for testing messaging entities.
Trying again to see if GitVersion works if
> Persisting message text

- README.md
> add superbus as an alternative tools

- .gitignore
- src/Common/Helpers/MessageAndPropertiesHelper.cs
- src/Common/Properties/AssemblyInfo.cs
- src/ServiceBusExplorer/Controls/TestControlBase.cs
- src/ServiceBusExplorer/Controls/TestEventHubControl.cs
- src/ServiceBusExplorer/Controls/TestQueueControl.cs
- src/ServiceBusExplorer/Controls/TestRelayControl.cs
- src/ServiceBusExplorer/Controls/TestTopicControl.cs
- src/ServiceBusExplorer/UIHelpers/LanguageDetector.cs
Enable using a blank greeting. 
Fixes #588 - "Hi mate, how are you?" cannot be changed and persisted
> Enable a blank greeting

- .github/workflows/handle-tag.yml
- .github/workflows/publish.yml
....even though I don't think it will help
> Upper casing secret reference 

- .github/workflows/handle-tag.yml
- .github/workflows/publish.yml
Passing the secret as a parameter instead
> Updated secret handling

- src/ServiceBusExplorer/Controls/HandleQueueControl.Designer.cs
- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
- src/ServiceBusExplorer/Controls/HandleSubscriptionControl.Designer.cs
- src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs
Adds a row number display to the row header in the DataGridView components on the Queue and Subscription dialog pages.
> adds row number display for queue and subscription messages

- README.md
Sadly have to specify Windows only 😞 
Fixes #719
> Added software requirements to readme

- README.md
One of the links did not work and the other link led to a page, but the video on that page is missing.
Fixes #715
> Removed Video section from readme.md

- src/Common/Helpers/TwoFilesConfiguration.cs
Hi,
here my fix to correct the bug #731
Regards
Robert
> Fix bug Wrong test made when saving two files configuration

- src/ServiceBusExplorer/Controls/HandleQueueControl.cs
Fix the currently sole, build warning.
> Fix build warning for null value

- src/Common/Common.csproj
- src/EventHubs/EventHubs.csproj
- src/NotificationHubs/NotificationHubs.csproj
- src/Relay/Relay.csproj
- src/ServiceBus/ServiceBus.csproj
- src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
- src/Utilities/Utilities.csproj
Also removed unused references.
> Updated NuGet packages including WindowsAzure.ServiceBus

- src/Common/Common.csproj
- src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj
- src/EventHubs/EventHubs.csproj
- src/NotificationHubs/NotificationHubs.csproj
- src/Relay/Relay.csproj
- src/ServiceBus/ServiceBus.csproj
- src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
- src/ServiceBusExplorer/ServiceBusExplorer.csproj
- src/Utilities/Utilities.csproj
Set warning as error on all projects
> Set warning as error on all projects

- src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj
- src/EventHubs/EventHubs.csproj
- src/Relay/Relay.csproj
- src/ServiceBus/ServiceBus.csproj
- src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
There is a vulnerability reported in Azure.Identity 1.12.0 that this PR fixes. It also upgrades some other NuGet packages.
> Raised NuGet versions

- .github/workflows/winget-submission.yml
Specified x64 architecture since the existing package is x64. I think this will work.... 
Is it possible to run .NET Framework 4.7.2 on a 32-bit OS?...
> Fix WinGet publishing

- src/ServiceBusExplorer/Forms/MainForm.cs
Add the number of queue/topics belonging to the root node of topics/queue
> Add number of queues/topis on the root node

- .github/workflows/winget-submission.yml
The publish to WinGet fails. Test this.
> Test to pass the GitHUb token another way

- src/ServiceBusExplorer/Forms/MainForm.cs
Fixes #843 (Creation of topics and queues no longer possible) by comparing Name instead of Text.
> Fix entity creation from tree
